#!/usr/bin/env bash

# Customizing a 404-error_page

# Updating Packages before performing installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Define the configuration file path
config_file="/etc/nginx/sites-available/default"  # Replace with your actual Nginx configuration file path

# Define the custom header line
custom_header="    add_header X-Served-By \$server_name;"

# Append the custom header line to the configuration file
if [ -f "$config_file" ]; then
    if ! grep -q "add_header X-Served-By" "$config_file"; then
        sed -i "/^}/i $custom_header" "$config_file"
        echo "Custom header added successfully to $config_file"
    else
        echo "Custom header already exists in $config_file"
    fi
else
    echo "$config_file does not exist"
fi

# test for errors 
sudo nginx -t

# restart nginx
sudo service nginx restart
