#!/usr/bin/env bash

# Update the package list
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend load_balancer
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server 150802-web-01 100.26.168.235:80 check
    server 150802-web-02 18.207.234.92:80 check
EOF

# Enable HAProxy init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Test haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart

