#!/usr/bin/env bash
# configure ufw to block all incoming and allow all outgoing traffic
#	on port 22, 443 and 80

sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 431/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
